### ISSUE TITLE
Bulk upload of media documents

### ISSUE THREAD

**Issue by billingb** [GCRC/nunaliit#1015]
Provide a new upload tool to upload multiple media files with a single schema and populate fields for all new media documents with specified values.

**Comment by ahayes** [comment]
Searched a bit for some examples of drag & drop supporting multiple files and folders of files. There are lots of people writing and rewriting these things. A few that caught my eye for one reason or another are below.

This one emphasizes that it queues the files up to avoid too many simultaneous connections:
https://code-boxx.com/simple-drag-and-drop-file-upload/

This one is based on jQuery:
https://makitweb.com/drag-and-drop-file-upload-with-jquery-and-ajax/

This one seems to show a list with separate progress status:
http://hayageek.com/drag-and-drop-file-upload-jquery/
