### ISSUE TITLE
Can't install couchdb

### ISSUE THREAD

**Issue by ilisaqativut** [GCRC/nunaliit#1033]
I'm trying to start out by install couchdb, but keep getting error messages?
<img width="702" alt="Screen Shot 2022-05-04 at 5 05 13 PM" src="https://user-images.githubusercontent.com/84241244/166833438-ba19129a-bff9-4cfc-b3de-312595a667bf.png">
<img width="693" alt="Screen Shot 2022-05-04 at 5 05 56 PM" src="https://user-images.githubusercontent.com/84241244/166833444-affd20d2-2906-489d-bf8e-1f8cd2d32e07.png">
 Help?

**Comment by ahayes** [comment]
Oh... I think Apache changed their repository address. Let me check. If that is the case I will update the tutorial wiki and reply again here.

**Comment by billingb** [comment]
Please see the correct repository on this documentation page: https://github.com/GCRC/nunaliit/wiki/Prerequisite-install-on-Ubuntu-18.04-LTS

Can you let us know where you found the above bintray URL? If it was in our docs we need to update it.

Thanks!

**Comment by ahayes** [comment]
Yeah, the old Apache CouchDB "bintray" repository address was still in the [tutorial wiki](https://github.com/GCRC/nunaliit_tutorial/wiki). I have replaced those lines.

@ilisaqativut could you please retry from step 3.3 in the tutorial and close this issue if that solved the problem?

**Comment by ahayes** [comment]
Hmm... If you are not able to close the issue, please just comment to let us know that it is fixed and I can close. Thank you so much for bringing this to our attention.

**Comment by ilisaqativut** [comment]
Thanks! I'll test it out tomorrow and close the comment if it works

**Comment by ilisaqativut** [comment]
Couchdb was installed, thanks!
