### ISSUE TITLE
Can't find testatlas

### ISSUE THREAD

**Issue by ilisaqativut** [GCRC/nunaliit#1034]
I'm on Step 7 trying to update and run a Nunaliit Atlas, but the update function doesn't seem to work. Sharing screenshots of my attempts to run to the atlas and how the nunaliit folder looks lik
<img width="720" alt="Screen Shot 2022-05-05 at 12 59 32 PM" src="https://user-images.githubusercontent.com/84241244/166984910-13bad7b1-a968-40ed-a7be-1ac566a1a78f.png">
<img width="722" alt="Screen Shot 2022-05-05 at 1 01 04 PM" src="https://user-images.githubusercontent.com/84241244/166984923-1105e011-1469-4e77-8342-bea63b18efcf.png">
e

**Comment by billingb** [comment]
You need to run the command from the base directory of the atlas (testatlas it appears) or you need to provide the atlas directory using the `--atlas-dir <dir>` flag. You can see all options for the update command by running `nunaliit help update`.

**Comment by ilisaqativut** [comment]
I don't understand to run from the base directory of the atlas. I'm using cd to enter testatlas (and moved it outside of the nunaliit folder), but it says it's not a director
<img width="642" alt="Screen Shot 2022-05-05 at 2 43 45 PM" src="https://user-images.githubusercontent.com/84241244/167013697-549627b4-30c2-4a20-8e27-262993326f1d.png">
y

**Comment by ilisaqativut** [comment]
I also tried just entering ../bin/nunaaliit update, but it says it can't connect to the server.
<img width="725" alt="Screen Shot 2022-05-05 at 3 07 01 PM" src="https://user-images.githubusercontent.com/84241244/167017167-2d06212b-1235-41c1-9b21-5cd6692526e5.png">

**Comment by billingb** [comment]
The second `nunaliit update` is progress over the problem you had before,
it recognizes that you are in an atlas directory and is now having trouble
connecting to couchdb. Is couchdb up and running and do you have the
correct username/password for the admin user configured? You can recheck
the configuration by running `nunaliit config` in the same location you ran
`nunaliit update`.

**Comment by ilisaqativut** [comment]
Hi,
I believe I typed in the configuration correctly. Was I supposed to use my own username and password rather than admin & admin_password
<img width="695" alt="Screen Shot 2022-05-05 at 5 37 30 PM" src="https://user-images.githubusercontent.com/84241244/167036326-bf03b2d2-d925-482c-aac8-b165b903d752.png">
?

**Comment by ilisaqativut** [comment]
Couchdb is up and running, and I've tried with the admin + admin_password and then my own username and password and neither works. 
Am I typing in the username and password incorrectly? admin + admin_password
Any help would be greatly appreciated, thanks!

**Comment by ahayes** [comment]
Is your couchdb admin password actually "admin_password"? You are supposed to type in the actual password at that step. And FYI, anything in the square brackets is what will be used if you don't type anything different in.

I'm sorry you are struggling with this but it looks like you may not have much linux command line or administration experience and that is going to make everything a bit harder for you. If you are willing to keep trying and posting screenshots, we'll do what we can to help but if you have a friend or relative who knows linux, maybe you can ask them for some help with the tutorial?

**Comment by ilisaqativut** [comment]
I got it to work finally! Thank you.
I was combining a combination of either admin and admin_password OR my actual login and actual password. I didn't think to use "admin" pared with my actual password.
