### ISSUE TITLE
Add triple attribute type and support it as an elementType in the array attribute type

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#1170]
Let's implement a new attribute type in Nunaliit for storing triples. There is a lot that can be done in the future for import/export and compatibility with existing standards and syntax, but for the initial Nunaliit implementation, we'll pattern this on Nunaliit's existing attribute types and schema definition configuration.

After some discussion with @pulsifer and some design work with @alexgao1, I am proposing that the new `triple` type be configured much like other types with type, id, and label keys and the addition of required subject, predicate, and object keys. These keys should themselves support a subset of existing Nunaliit attribute objects starting with `string`, `localized`, `reference`, and `selection` types. The important considerations when deciding on the syntax for the configuration and resulting document structures were to be consistent, familiar, flexible, and useful. The intent is to benefit from lots of code reuse for schema building, document display, and form rendering to build a simple way of creating something akin to Nunaliit's existing reference objects but which have explicit subjects and objects and the ability to specify a predicate.

The following schema definition syntax example for a single triple attribute consisting of a string attribute for the subject key, a predicate key consisting of a hard-coded selection list, and an object key again consisting of a string:

```
{
	"type": "triple",
	"label": "Placename with Meaning",
	"id": "placename_with_meaning",
	"subject": {
		"label": "Placename",
		"type": "string",
		"id": "placename"
	},
	"predicate": {
		"type": "selection",
		"id": "predicate",
		"options": [
			{
				"label": "has meaning",
				"value": "has_meaning",
				"isDefault": true
			}
		],
		"excludedFromDisplay": true,
		"excludedFromForm": true
	},
	"object": {
		"label": "Meaning",
		"type": "string",
		"id": "meaning",
		"textarea": true
	}
}
```

If used to create an example schema named "myschema01", a resulting document with that schema might look like this:

```
{
	"_id": "123",
	"_rev": "321",
	"nunaliit_schema": "myschema01",
	"myschema01": {
		"placename_with_meaning": {
			"nunaliit_type": "triple",
			"subject": {
				"placename": "Amosville"
			},
			"predicate": {
				"predicate": "has_meaning"
			},
			"object": {
				"meaning": "Who knows"
			}
		}
	}
}
```

A schema that required an array of these triples might have an attribute definition like this:
```
{
    "type": "array",
    "id": "placenames_with_meanings",
    "elementType": "triple",
    "elementOptions": {
        "subject": {
            "label": "Placename",
            "type": "string",
            "id": "placename"
        },
        "predicate": {
            "type": "selection",
            "id": "predicate",
            "options": [
                {
                    "label": "has meaning",
                    "value": "has_meaning",
                    "isDefault": true
                }
            ],
            "excludedFromDisplay": true,
            "excludedFromForm": true
        },
        "object": {
            "label": "Meaning",
            "type": "string",
            "id": "meaning",
            "textarea": true
        }
    }
}
```

If used to create an example schema named "myschema02", a resulting document with that schema might look like this:

```
{
    "_id": "123",
    "_rev": "321",
    "nunaliit_schema": "myschema02",
    "myschema02": {
        "placenames_with_meanings": [
            {
                "nunaliit_type": "triple",
                "subject": {
                    "placename": "Amosville"
                },
                "predicate": {
                    "predicate": "has_meaning"
                },
                "object": {
                    "meaning": "Who knows"
                }
            },
            {
                "nunaliit_type": "triple",
                "subject": {
                    "placename": "Alexville"
                },
                "predicate": {
                    "predicate": "has_meaning"
                },
                "object": {
                    "meaning": "Who knows"
                }
	    }
        ]
    }
}
```

This work should probably be carried out in a branch attached to a PR. We might have to iterate a bit and test with a few atlases to get a good first release of this feature. Once we are happy with the triple and array of triple configuration and behaviour, the ability to add and configure these attribute types should be added to the schema builder tool as well.

**Comment by kunwarj** [comment]
For array of triple, the example above shows that we are using option key to hold the triple structure. But we have options key used for selections type as well. 
@alexgao1 @billingb @ahayes

**Comment by kunwarj** [comment]
shouldn't  `"elementType": "triple"` this be on the root instead of defining inside the options for consistency?

**Comment by ahayes** [comment]
Sorry, @kunwarj . You are correct. I have revised the configuration example. Can you and @alexgao1 have another look please?

**Comment by ahayes** [comment]
@alexgao1 I have added a blurb about the schema builder to the issue description but we may want to use the implementation in an atlas or two to make sure we are happy with the implementation before adding it to the GUI schema builder tool.
