### ISSUE TITLE
OL6 canvas geometry creation from edit bar creates [object Object] in geometry/WKT field

### ISSUE THREAD

**Issue by alexgao1** [GCRC/nunaliit#1193]
#1192

**Comment by ahayes** [comment]
I flagged it as an enhancement because I didn't think we were supporting feature creation/editing in the new OL6 map canvas yet. If this enables it, that's great!

**Comment by alexgao1** [comment]
The typical editing functions should work, although this new edit bar has some other features that are untested/unconfirmed if they behave properly/at all yet.
