### ISSUE TITLE
Array position change UI broken

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#1205]
The small arrow icons used to change the position of the elements of an array in a form are not working as expected. This was observed when attempting to re-order an array of triples. I don't recall this being an issue before the triple code merge, but it may have been.

**Comment by alexgao1** [comment]
https://github.com/GCRC/nunaliit/issues/648

**Comment by ahayes** [comment]
Thanks @alexgao1 and @kunwarj !
