### ISSUE TITLE
Add atlas builder translation files

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#131]
Currently, the Nunaliit framework loads files based on the requested locale to accommodate translation of the tool. These files are located in the subdirectory "nunaliit2" and are named with a scheme that follows: nunaliit2.&lt;lang&gt;.js

For example, the file containing the French translations for Nunallit is named: nunaliit2.fr.js

At run-time, the localization service looks up the current locale and adds a &lt;script&gt; tag to include the appropriate translation file. This is to avoid loading large files containing replacement strings when it is not needed.

This enhancement is to extend this logic to translation files provided by atlas builders. Currently, the only ways for atlas builders to include their translated strings is via the database (not recommended), by adding the translated strings to the current Nunaliit files (not recommended), or by including all the translation files in the HTML document (not efficient).

The framework should load files with a naming scheme reserved for the atlas builder. A possible approach would be to load, via a script tag, files that follow the following scheme: ./atlas.&lt;lang&gt;.js   Using this approach, if the locale was French, then the following file would be loaded: atlas.fr.js

**Comment by ahayes** [comment]
The implementation of the feature actually ended up using a different naming convention for atlas-specific translation files. See the [Translation Files](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#translation-files) section in the [Nunaliit Documentation for Atlas Builders](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders) for details.
