### ISSUE TITLE
Provide a mechanism to allow a given layer to function as a Public layer

### ISSUE THREAD

**Issue by pulsifer** [GCRC/nunaliit#139]
Nunaliit has a system Layer called Public that allows anyone using the Atlas to add a feature.  This can be problematic when you would like to organize features added by users layer.  It would be very useful to allow an Atlas builder to assign any layer "Public" functionality (i.e. user can add features without being the Manager of that layer).

**Comment by jpfiset** [comment]
As I was reviewing the code, the validate_doc_update has been modified to assume that any layer named with a prefix of 'public_' is considered a public layer.
