### ISSUE TITLE
Helpful error should be reported when sensitive.properties file is missing

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#179]
When an atlas is checked out from source repository, it usually lacks the config/sensitive.properties file. Running update on an atlas in that state return a NPE.

There is probably a more informative way to handle this situation.

**Comment by boikle** [comment]
Just tested this, and can confirm this is still an issue. CLI outputs "Error: null" when attempting to either update or run nunaliit in atlas dir
