### ISSUE TITLE
Chrome bug causing problems with hover sounds

### ISSUE THREAD

**Issue by pulsifer** [GCRC/nunaliit#184]
This does not require action from the Nunaliit team, however it may save some folks in the Nunaliit community some time and frustration.  We are seeing this behaviour on one of our atlases.

https://discussions.apple.com/thread/5790962?tstart=0

**Comment by ahayes** [comment]
This should not be an issue in recent Nunaliit builds as we now use [Media Element](https://www.mediaelementjs.com/) for multimedia handling.
