### ISSUE TITLE
dumping - but maintaining relationships

### ISSUE THREAD

**Issue by afitzgerrell** [GCRC/nunaliit#247]
Hi,

Currently, if I run a dump of a specific document id, just the items surrounding that id are dumped and I have to check and specify another dump to include any related items' ids.

Is there a way to dump a document, or number of documents, and preserve the relationships of those documents to other documents or media?

Thanks,

amy

**Comment by ahayes** [comment]
As an update, the dump command can now filter by layer. Another solution is to use filtered replication as documented by the CouchDB maintainers.
