### ISSUE TITLE
Data Modification tool should include query by view

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#27]
In the Data Modification tool (tools/select.html), there should be a query method that is based on a CouchDb view. This method should allow to specify start/end keys, or specific keys.

**Comment by boikle** [comment]
This issue has been resolved in the data modifications tool. To perform a query by view with the data modification tool, perform the following steps; 

1. Click the "Add" queries button
1. Select the query type "Select documents reported in a view"
1. Select the view by it's name
