### ISSUE TITLE
Add Edge Radial Canvas to standard set of canvases

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#299]
This enhancement is to add a canvas that allows a user to observe the connections between documents using a technique presented by Mike Bostock as "Hierarchical Edge Bundling". An example can be seen here:

http://bl.ocks.org/mbostock/7607999

**Comment by boikle** [comment]
I believe this issue has been resolved with the creation of both the Radial Tree Canvas and Collapsible Radial Tree Canvas. See both [Radial Tree Canvas](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#atlas_canvas_radial_tree) and [Collapsible Radial Tree](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#atlas_canvas_collapsible_radial_tree) in the wiki documentation.
