### ISSUE TITLE
Panoramic images do not show up on Safari

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#300]
Issue is on Safari 6.0.1

The image shows up on the right. However, when clicking on the image, the presentation box comes up but the image fails to load.

**Comment by ahayes** [comment]
Also happens on Safari Version 7.1.2 (9537.85.11.5)

**Comment by jpfiset** [comment]
First, WebGL is not turned on, by default, for Safari 6.

http://onvert.com/guides/enable-webgl-safari/

Open the Safari menu and select Preferences.
Then, click the Advanced tab in the Preferences window.
Then, at the bottom of the window, check the Show Develop menu in menu bar checkbox.
Then, open the Develop menu in the menu bar and select Enable WebGL.

**Comment by jpfiset** [comment]
It would be nice to detect when WebGL is not present and let the user know.

**Comment by jpfiset** [comment]
There is still an error preventing the image from appearing:

"THREE.WebGLRenderer: elementindex as unsigned integer not supported"

**Comment by boikle** [comment]
Just viewed a panoramic image in a Nunaliit atlas with Safari v. 11.1.2 (11605.3.8.1). Pan Image worked as expected. I believe this can be closed now.
