### ISSUE TITLE
Problems exporting geometries

### ISSUE THREAD

**Issue by pulsifer** [GCRC/nunaliit#307]
I am trying to export geometries using the Data Modification Application.  A query was created using "select geometries from layer".  When the Export Geometries tool is used, an error is presented in the browser. 

HTTP ERROR: 500
Problem accessing /servlet/export/export/export.geojson. Reason:

    javax.servlet.ServletException: Error during export process
Powered by Jetty://
Inspecting the log (excerpt below) suggests that there is a problem with the Geometry value.  

A query was run to identify invalid layers. No invalid documents exist in the layer.

***  QUESTION ***   Is there an easy way to identify the problematic geometry(ies) within a document?  The log does not seem to provide details in terms of the document(s) that is failing.  

Partial Log Output:
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error occurred while parsing a WKT string
        at ca.carleton.gcrc.geom.wkt.WktParser.parseGeometry(WktParser.java:67)
        at ca.carleton.gcrc.geom.wkt.WktParser.parseWkt(WktParser.java:31)
        at ca.carleton.gcrc.geom.wkt.WktParser.parseWkt(WktParser.java:26)
        at ca.carleton.gcrc.couch.export.impl.ExportFormatGeoJson.outputExport(Expor
tFormatGeoJson.java:112)
        at ca.carleton.gcrc.couch.export.impl.ExportFormatGeoJson.outputExport(Expor
tFormatGeoJson.java:56)
        at ca.carleton.gcrc.couch.export.ExportServlet.doPost(ExportServlet.java:243
)
        ... 18 more

**Comment by jpfiset** [comment]
Here is a filter script for the modification tool. Hopefully, it can detect the invalid geometry.

```javascript
function(doc){
	if( doc 
     && doc.nunaliit_geom ){
        if( !doc.nunaliit_geom.wkt ){
            return true;
        };
        
        var geom = OpenLayers.Geometry.fromWKT(doc.nunaliit_geom.wkt);
        if( !geom ){
            return true;
        } else if( !isValidOlGeom(geom) ) {
            return true;
        };
	};

    function isValidOlGeom(geom){
	    if( geom.components ){
		    for(var i=0,e=geom.components.length; i<e; ++i){
			    var c = geom.components[i];
			    if( !isValidOlGeom(c) ){
				    return false;
			    };
		    };
	    } else {
		    if( geom.x !== geom.x ){
			    return false;
		    };
		    if( geom.y !== geom.y ){
			    return false;
		    };
	    };
	
	    return true;
    };

	
	return false;
}
```

I have re-opened Issue #194

**Comment by pulsifer** [comment]
I have run the script using the modification tool -> Transform -> Javascript Replace.  Unfortunately, it does not run (progress remains at 0%).  I will do my best to sort out the issue.

**Comment by jpfiset** [comment]
This is not a transformation script, it is a filter script. You can use it in two ways:
- Queries -> Add -> Select from Javascript
- All Document -> Refine List -> Select from Javascript

This will create a new list containing documents with invalid geometries. It is difficult to write a script to fix the issues with the geometries until we understand what the problem is. Therefore, I can not really provide you a transformation script.

**Comment by pulsifer** [comment]
Thanks.  I have managed to run the script, however it does not identify any problematic geometries.  Nor does the Select Invalid Documents result in any hits.  There seems to be some other issue at play here.  I have tried to export documents using a select by schema approach and the export geometry process completes and creates a file, however the file is incomplete (terminates in the middle of a document part way through the list).  Not sure how to identify the problem as there are over 400 documents involved.

**Comment by jpfiset** [comment]
Can you dump your database and send it to me?

**Comment by jpfiset** [comment]
Document: 827f6eecb96bdd33f899a11f886f7ba8

MULTIPOINT((-166.53667  53.87361)

should be

MULTIPOINT((-166.53667  53.87361))

**Comment by jpfiset** [comment]
Here is an improved filter script to catch un-balanced parenthesis:

```javascript
function(doc){
    if( doc 
     && doc.nunaliit_geom ){
        if( !doc.nunaliit_geom.wkt ){
            return true;
        };

        var geom = OpenLayers.Geometry.fromWKT(doc.nunaliit_geom.wkt);
        if( !geom ){
            return true;
        } else if( !isValidOlGeom(geom) ) {
            return true;
        };
        
        var openCount = countChar(doc.nunaliit_geom.wkt,'(');
        var closeCount = countChar(doc.nunaliit_geom.wkt,')');
        if( openCount != closeCount ){
            return true;
        };   
    };

    function isValidOlGeom(geom){
        if( geom.components ){
            for(var i=0,e=geom.components.length; i<e; ++i){
                var c = geom.components[i];
                if( !isValidOlGeom(c) ){
                    return false;
                };
            };
        } else {
            if( geom.x !== geom.x ){
                return false;
            };
            if( geom.y !== geom.y ){
                return false;
            };
        };
    
        return true;
    };

    function countChar(str,c){
        return str.split(c).length - 1;
    };

    return false;
}
```
