### ISSUE TITLE
Map Orientation Widget - not functioning fully in Firefox

### ISSUE THREAD

**Issue by afitzgerrell** [GCRC/nunaliit#314]
I'm testing the functionality of the orientation widget in the ArcticCBM prototype atlas at GCRC (http://devel.gcrc.carleton.ca:8098/index.html) and notice that in both Safari and Chrome, the widget populates with a north polar stereo background and longitude lines (the latter being much more pronounced in Safari (7.1.4) and very faint in Chrome (41.0.2272.101)), in addition to clickable arrowheads that highlight blue as my cursor crosses over them in the widget to change the map projection - this is not the case for me when viewing the atlas in Firefox (36.0.4).  

In Firefox, the widget is not sporting a background image, but transparent, and the arrowheads are largely not clickable to change the map projection, except for the one that defaults to EPSG:3571.  That one, when I hover into the widget, highlights blue and is clickable.  The others remain black as my cursor hovers over them and I have to click on the base layer options to change map projection.
![browser_orientation_widgets](https://cloud.githubusercontent.com/assets/8062694/6814028/81bfa0ca-d240-11e4-9bd1-2dc0b78bb795.png)

Please let me know if you have any questions or need more detail.

Thanks,

Amy

**Comment by jpfiset** [comment]
I believe that I have fixed this issue. I updated the test site (http://devel.gcrc.carleton.ca:8098/index.html).

Can you check if it works for you?

**Comment by afitzgerrell** [comment]
Thanks, JP!

I have just tested and it looks to be functioning well in Firefox now and the widget looks consistent, style-wise, across all three browsers to boot.
