### ISSUE TITLE
Clusters menu: Related documents displaying differently in map depending on browser - consistent in sidebar though

### ISSUE THREAD

**Issue by afitzgerrell** [GCRC/nunaliit#318]
Depending on which browser I'm using to view the prototype ArcticCBM atlas when I hover over a cluster of merged features, associated documents display differently in the maps of the different browsers and only one or two show as related, typically.  The projects listed in the right pane are consistently what I'd expect to see though.  Screen grabs are better than words, so attaching six...two each from my three browsers showing two different cases of clustering display differences.
![firefox clusters](https://cloud.githubusercontent.com/assets/8062694/6859283/ce44051a-d3dc-11e4-9f22-a708cfec2819.png)
![chrome clusters](https://cloud.githubusercontent.com/assets/8062694/6859287/d77f8c58-d3dc-11e4-9396-a55686b070f1.png)
![safari clusters](https://cloud.githubusercontent.com/assets/8062694/6859292/dd77c698-d3dc-11e4-9c65-3269bc9009f0.png)
![firefox 2](https://cloud.githubusercontent.com/assets/8062694/6859312/22609294-d3dd-11e4-8f07-9cef4a8e9fe5.png)
![chrome 2](https://cloud.githubusercontent.com/assets/8062694/6859313/25ed56ea-d3dd-11e4-9471-c10a3ad97f8c.png)
![safari 2](https://cloud.githubusercontent.com/assets/8062694/6859316/27d70424-d3dd-11e4-8084-76a5219071a3.png)
Safari consistently doesn't show anything other than the cluster I've clicked, and continue to hover over, as highlighted.  Chrome and Firefox vary in what besides the cluster feature is highlighted in the map.

**Comment by jpfiset** [comment]
I have updated the test site. This problem should be fixed.
