### ISSUE TITLE
Invalid fields found on Geometries imported from GeoJSON

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#32]
When importing a GeoJSON file, the following issues have been reported:
1. WKT points have un-necessary line breaks (\n)
2. The nunaliit_created and nunaliit_last_updated fields have invalid values that looks like a Java identifier:

ca.carleton.gcrc.couch.onUpload.conversion.CreateUpdateInfo@1db4492

**Comment by boikle** [comment]
Is this still an issue? I've never experienced this issue with Nunaliit Import tool, so I suspect it was addressed by JP.

**Comment by ahayes** [comment]
Agreed. I have not seen it either.
