### ISSUE TITLE
Add "found" state to the style

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#322]
The find state is handled generically. However, the styling system does not provide default values for the elements that are found.

The style definitions should be augmented with a "found" attribute. The style system should handle it accordingly.

**Comment by boikle** [comment]
The "found" state is part of the new conditional styling system. See [wiki documentation](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#atlas_content_map_styles_conditional) for further details on this style system.
