### ISSUE TITLE
Add ability to insert media view in introduction text

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#333]
Some of the classes handled by the show service require a document. In introduction text, a document is not in context. Some of those classes should be functional in the introduction by specifying the desired document as an attribute of the element.

The first one needed is n2s_insertMediaView

**Comment by boikle** [comment]
This issue has been resolved with the creation of **n2s_insertMediaView** show service. See (wiki section on the show service)[https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#atlas_content_show_service] for further details. 

**Usage example:**
```html
<div>
	<span class="n2s_insertMediaView" nunaliit-document="12345" nunaliit-attachment="my_picture.jpg">My Picture</span>
</div>
```
