### ISSUE TITLE
Add alternative visualizations

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#34]
Would be good to consider some of the available visualization libraries to see what is required to support them in Nunaliit and if there are any that fit the model better than others.

Some projects to consider for alternative visualization and interaction:

http://arborjs.org/

http://d3js.org/

http://philogb.github.com/jit/index.html

Bunch more listed at http://selection.datavisualization.ch/

**Comment by boikle** [comment]
d3js was added to nunaliit
