### ISSUE TITLE
Localization of framework strings

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#343]
Would it be possible to add localization for specific strings used in the framework, such as: "Loading ...", "search the atlas" and "Cancel".

Alternatively these could be replaced with universal/language free icons (eg. spinning progress wheel, magnifying glass, and red x)?

**Comment by jpfiset** [comment]
Can you provide information about which "Cancel" button is not respecting the localization?

**Comment by jpfiset** [comment]
As far as the custom search label, you must localize it before passing it to Nunaliit. This is an example:

````js
var _loc = function(str,args){ return $n2.loc(str,'iran',args); };

...

customService.setOption('searchWidgetText',_loc('search the Atlas'));
````

**Comment by jpfiset** [comment]
As far as the "Cancel" button is concerned, you must provide a translation in Farsi. It is not yet provided by your atlas.
