### ISSUE TITLE
Adding new language to language_switcher

### ISSUE THREAD

**Issue by pulsifer** [GCRC/nunaliit#345]
I am attempting to add another language to an atlas built on the Nunaliit demo template.  The alternative  language being used in Inuktitut (code = iu).  Alternate strings have been added to a number of the atlas documents.  For example, the primary module file now includes:

{
	"nunaliit_type":"localized"
	,"en":"New Atlas"
	,"fr":"Atlas Nouveau"
	,"iu":"ᐃᓄᒃᑎᑐᑦ"
}

In the title.json file.  A new file (iu.html) has been added to the module/introduction/content folder. 

I have also done this for the navigation folder, help.browsers, approved and public layers etc.
A file called nunaliit_lang.iu.js in the htdocs folder has been created.

While the markup required for documents is clear to me, it is not clear how to enable the new language in the language_switcher widget.  Is there a configuration file that must be modified to add the new language?  Currently, choosing the Language widget only presents English, French and Default as language options.

Apologies if I have missed this in the documentation.

**Comment by jpfiset** [comment]
In nunaliit_custom.js:

````js
var langDef = {
	code: 'xx',
	name: 'Language X'
};

config.directory.languageService.addLanguage(langDef);
````
