### ISSUE TITLE
is it possible to set links within db docs to open in a new tab by default, rather than current window?

### ISSUE THREAD

**Issue by afitzgerrell** [GCRC/nunaliit#367]
Most of the project documents in the NSIDC ArcticCBM atlas contain links to the projects' websites or, additionally other links for data available, etc.  Yet, when the link is clicked, the browser switches to displaying the project website, leaving the ArcticCBM atlas.  I know that if I hold the command key (apple) and presumably the control key (windows) that the link will open in a new tab - but users in general may or may not know this so we'd like to be able to click the link and, by default, have it open in a new tab.  Is there as setting in Nunaliit that will allow this to be the default action for links within documents that are stored in the CouchDB?

Please let me know if you have any questions - Amy.  

![screen shot 2015-08-28 at 1 00 53 pm](https://cloud.githubusercontent.com/assets/8062694/9554681/e0f16e6a-4d84-11e5-8e45-979393cfefcb.png)

**Comment by jpfiset** [comment]
It is regarded as bad practice to open new windows when clicking on a link. Nunaliit used to open new windows for some content, but we have been discouraged from doing this. There are some browsers, like ones found on smart phones, that have a limit on the number of available tabs.

Therefore, Nunaliit does not offer any code to help with this.

That said, you can accomplish that yourself in your schema. Looking at your schema for arcticcbmProjectDoc, I find the following excerpt:

````
                {{#project_website}}
		<div>
			<div class="label n2s_localize">Project website: </div>
			<div class="value"><a href="{{.}}">{{.}}</a></div>
			<div class="end"></div>
		</div>
                {{/project_website}}
````

I believe that if you modified the link to

````
<a href="{{.}}" target="_blank">{{.}}</a>
````

it would probably accomplish what you wish.

Ref: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target

**Comment by afitzgerrell** [comment]
Thanks JP - I’ll give this a go and see if it does the trick.

Amy
On Aug 31, 2015, at 11:51 AM, Jean-Pierre Fiset <notifications@github.com> wrote:

It is regarded as bad practice to open new windows when clicking on a link. Nunaliit used to open new windows for some content, but we have been discouraged from doing this. There are some browsers, like ones found on smart phones, that have a limit on the number of available tabs.

Therefore, Nunaliit does not offer any code to help with this.

That said, you can accomplish that yourself in your schema. Looking at your schema for arcticcbmProjectDoc, I find the following excerpt:

                {{#project_website}}
        <div>
            <div class="label n2s_localize">Project website: </div>
            <div class="value"><a href="{{.}}">{{.}}</a></div>
            <div class="end"></div>
        </div>
                {{/project_website}}
I believe that if you modified the link to

<a href="{{.}}" target="_blank">{{.}}</a>
it would probably accomplish what you wish.

Ref: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target

—
Reply to this email directly or view it on GitHub.


—
Amy FitzGerrell
Data Operations Analyst
National Snow and Ice Data Center
Ph: 303.492.5692
Web: http://nsidc.org/

**Comment by ahayes** [comment]
Hi Amy. JP is right that it is not a great idea to open new windows and tabs for people. People who are proficient with their browser will likely be grumpy that you have changed the default behaviour, and people who aren't proficient may not be able to figure out how to get back. The back button they depend on won't work anymore if you open a new window/tab and they may not realize that you have popped a new window/tab in front of the old one. My experience in the communities we work with is that most people fall into the later camp.

Anyhow, it is an issue that has plagued all web designers over the years but I think the web has generally settled on letting the user learn to use the browser and make those decisions. By default, the most important thing for novice users seems to be making sure the back button works as expected.

**Comment by afitzgerrell** [comment]
Many thanks Amos,

I’ll pass these details from you and JP along to our partners at ICC so that they are aware of the potential pitfalls and reasoning behind the current link behavior.

Amy 
On Aug 31, 2015, at 12:21 PM, Amos Hayes <notifications@github.com> wrote:

Hi Amy. JP is right that it is not a great idea to open new windows and tabs for people. People who are proficient with their browser will likely be grumpy that you have changed the default behaviour, and people who aren't proficient may not be able to figure out how to get back. The back button they depend on won't work anymore if you open a new window/tab and they may not realize that you have popped a new window/tab in front of the old one. My experience in the communities we work with is that most people fall into the later camp.

Anyhow, it is an issue that has plagued all web designers over the years but I think the web has generally settled on letting the user learn to use the browser and make those decisions. By default, the most important thing for novice users seems to be making sure the back button works as expected.

—
Reply to this email directly or view it on GitHub.


—
Amy FitzGerrell
Data Operations Analyst
National Snow and Ice Data Center
Ph: 303.492.5692
Web: http://nsidc.org/
