### ISSUE TITLE
question about cluster and zoom to projects

### ISSUE THREAD

**Issue by afitzgerrell** [GCRC/nunaliit#369]
Currently, at the request of our partners, I have disabled the cluster functionality that listed the clustered projects in the details pane of the ArcticCBM atlas so that when a user clicks on a cluster, they're zoomed in.  What ICC's looking for in the zoom-to cluster functionality though is to be able to click just once on the cluster symbol to zoom straight into whatever tile level is necessary to display all of the (formerly) clustered projects individually.  Is this something that is currently feasible, or could be made so?

I tried to see if this could be achieved by changing the cluster distance, but that is not getting me where the partners want to go.  With the cluster distance set to 20, it takes six clicks (at project-dense Clyde River, NU) to get to all projects shown individually, and during the clicking, sub-clusters are displayed which is something our partners want to avoid.  If I reduce the cluster distance to five, I can reduce the number of clicks at Clyde River's cluster to four, but it's still clustering the projects in one, then one, then three, then five cluster features before all projects are revealed at the fourth click.  

I also fiddled with the cluster threshold setting, but that led to Issue #360.

Please let me know if you have any questions.
Thanks,
Amy

**Comment by ahayes** [comment]
Hi Amy.

I understand what you are trying to do. From a generic Nunaliit perspective where we don't know what the data looks like,  zooming automatically until there is no clustering left typically leaves some of what was in the cluster off screen. There is no tree hierarchy or sub-clusters, although I understand why it might look that way. It is simply lumping features that are too close together into a cluster - and it re-evaluates each time you zoom & pan the map. Clicking on a cluster just zooms one zoom level.

I think we need to step back and look at the data model in this case. I do not think that in your atlas, all those Clyde projects are scattered around the landscape like that. I'm imagining that what would be useful is something more akin to http://atlas.cpha.ca where the goal is to get a list of the projects when clicking on the cluster, not to mess about with the map.

Perhaps it is time to engage us in a design discussion with the ICC gang?

**Comment by afitzgerrell** [comment]
Hi Amos,

I'm just in the midst of an email back to Laura Petrunka regarding a number of changes I've made that she requested, so I will let her know of your suggestion to contemplate holding a design discussion and see what she thinks.

Many thanks,
Amy

**Comment by ahayes** [comment]
Taken to email/offline.
