### ISSUE TITLE
Schema Definition File - Text Area - Missing option

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#370]
Text areas defined with a schema definition need the option to define max height value. Currently the default is set to 100 and to change it, the display.txt file needs to be updated directly.

**Comment by jpfiset** [comment]
Added two options:
- "maxHeight"
- "disableMaxHeight"

**Comment by ahayes** [comment]
Actually, I think the default should be that maxHeight is disabled and there should be an enableMaxHeight option.

**Comment by ahayes** [comment]
Simple solution. TY.
