### ISSUE TITLE
Support Wiki mark up in schema display

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#375]
Wiki is a useful mark up for generating HTML. Might be useful to end users.

**Comment by ahayes** [comment]
If we are going to go with a syntax, I'd prefer something like Markdown to be more compatible with our docs, etc.

Have a look at this and the bits he's using: http://jbt.github.io/markdown-editor/

**Comment by ahayes** [comment]
Also have a look at:

https://github.com/benweet/stackedit
http://dillinger.io/

**Comment by jpfiset** [comment]
This effort requires wiki support because we are porting pages from an existing wiki to a Nunaliit framework.

Here is another ticket for the markdown suppot:
#377
