### ISSUE TITLE
Allow the Import tool to import data in csv format

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#385]
It would be nice if the import tool could import data in csv format so that conversion to json wouldn't be required.

**Comment by ahayes** [comment]
How about integrating this for parsing CSV in browser?

https://github.com/mholt/PapaParse

**Comment by boikle** [comment]
This issue has been resolved. See wiki on [CSV Import profiles](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#importing_data_profile_csv).
