### ISSUE TITLE
Re-import comparison/update error for fixed named keys

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#386]
When re-importing a dataset, it appears that when a key is fixed (removing invalid characters, eg. '%'), the atlas does not appear to compare and update values based on the old imported key and the new corrected key in the document. 

**Eg of what I think is happening:**

field %_grade when imported the first time will become the key _grade in the document, but when the %_grade value is updated and re-imported the comparison between %_grade and _grade may not be happening, and subsequently no update occurs.

**Comment by jpfiset** [comment]
I observed a bug in the import tool when attempting to resolve a collision on a fixed attribute named "%_grade". However, I am not able to reproduce the problem mentioned.

Please, submit import profile, the erroneous import entry and the associated document. Thanks.

**Comment by jpfiset** [comment]
After discussion with Rob, the error was found in the original data.
