### ISSUE TITLE
Suggestion: Schema option to define input form text box placeholder value

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#397]
**Suggestion: **
Could an option be provided in the schema definition to set the placeholder value for a input form text box?

**Comment by ahayes** [comment]
What a great idea! ;)

It looks like some HTML5 form elements (input and textarea for example) can have a placeholder attribute such as:
`<input type="text" placeholder="http://example.com" />`

Being able to set that in the schema definition.json would be great.
