### ISSUE TITLE
Possible Bug?: Tiled Display create document issue

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#408]
**Possible Issue**:
When creating a new document when the display is set to tiled, new documents were not storing values input in the form view, upon the initial creation of the document (I.e. the display would show no values stored in the display view). When the document was edited however, those edited values would be stored in the document. 

Note: Attempts  to reproduce this bug were not successful. So this may be a one off problem, but thought I should report it regardless.

**Comment by jpfiset** [comment]
If you can not reproduce the problem, can we close it?
