### ISSUE TITLE
Add Splash Page widget

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#411]
Add a widget to show a splash page, controllable by data found in the database. Splash page should be seen on page load. When dismissed, it should be ignored from this point on (cookie)

**Comment by ahayes** [comment]
Is the widget per module or per atlas? I would think per module would be best.

Also, whether or not it is seen again could be an option on the widget. I wonder if we should also provide an option for a user selectable 'Don't show this again' checkbox next to the 'Enter site' dismiss button.

**Comment by ahayes** [comment]
The content of the splash might change and it might need to be shown to all users again, ignoring any previous cookies or checkboxes too.
