### ISSUE TITLE
Add Custom Service option for updating title text in the "Select Language" dialog window

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#423]
**Suggestion:**
Would it be possible to create a custom service option for updating the title text in the select language window title, similar to the manner the search box text can be updated?

**Example:**
Changing the title text from "Select Language" to "Pick a Language"

**Comment by jpfiset** [comment]
This can be accomplished by offering an English to English translation. This can be done by putting the following content into the file "nunaliit_lang.en.js", located in htdocs:

<pre>
;(function($n2){

$n2.l10n.addLocalizedStrings("en",{
"Select Language":"Pick a language"
});

})(nunaliit2);
</pre>
