### ISSUE TITLE
Bug/Suggestion: update-schema can't initially find a schema if it's name is changed

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#433]
**Situation:** If I add a schema called  'testschema', then decide to change the name of the schema from 'testschema' to 'test' by renaming the folder, the id of the schema in the definition file and _id.txt file. I will need to run the command update-schema --name testschema first because nunaliit can't find a schema called test. After this initial update with the old name, the command update-schema --name test will work. 

**Suggestion:** Would it be possible to have the update-schema command work without requiring an update using the old schema name?

**Comment by boikle** [comment]
Follow-up: After thinking about this issue some more, I tried updating the name.txt file as well, and the update-schema --name command now works as expected.

**Comment by jpfiset** [comment]
What would be the steps you would like to see?

Here is one possible scenario. A schema named "testschema" was generated from a schema definition. A user decides to change the name from "testschema" to "test". The following steps are used:
1. Edit the definition.json file associated with the schema and change the "id" attribute from "testschema" to "test"
2. Run command line "nunaliit update-schema --name test"

Would that work?

I am not sure, but I believe that, currently, the same steps work if the command line is: "nunaliit update-schema --name testschema"

It would also work if the command line was "nunaliit update-schema --all"

To make the offered steps work as presented, a change to nunaliit would be required. I think what is required is:
1. If named schema is not found, load all schemas
2. From schemas loaded, attempt to recompute name from definitions, if available
3. If at that point a name matches the requested one, using the schema associated with the name
