### ISSUE TITLE
Establishing default layer when adding a new feature

### ISSUE THREAD

**Issue by pulsifer** [GCRC/nunaliit#465]
When adding a new feature I would like to establish a default layer that is not the "public" layer.  This will allow users to avoid the step of clicking the Layers button and explicitly selecting a layer.

It would seem that this could be done by adding the following to the "create" attribute of a schema:

   "nunaliit_layers": ["new_default_layer"]

When I do this, no error is reported, however new features are created with a value of:

**Comment by jpfiset** [comment]
Duplicate to #466
