### ISSUE TITLE
Establishing default layer when adding a new feature

### ISSUE THREAD

**Issue by pulsifer** [GCRC/nunaliit#466]
When adding a new feature I would like to establish a default layer that is not the "public" layer.  This will allow users to avoid the step of clicking the Layers button and explicitly selecting a layer.

It would seem that this could be done by adding the following to the "create" attribute of a schema:

   "nunaliit_layers": ["new_default_layer"]

When I do this, no error is reported, however new features are created with 
   "nunaliit_layers": ["public"]

What is the best way to change the default layer when a new feature is added?

**Comment by jpfiset** [comment]
What version of Nunaliit are you using?

**Comment by pulsifer** [comment]
2.7 SNAPSHOT.

**Comment by jpfiset** [comment]
In nunaliit_custom.js:

In window.nunaliit_custom.configuration(config, callback) function
````js
var moduleDisplay = null;

// Handler called when the module content is loaded
dispatchService.register(DH,'reportModuleDisplay',function(m){
	moduleDisplay = m.moduleDisplay;
});

dispatchService.register(DH, 'preDocCreation', function(m, addr, dispatcher){
	handlePreDocCreation(m,moduleDisplay,dispatcher);
});

````

````js
function handlePreDocCreation(m,moduleDisplay,dispatchService){
	var moduleId = undefined;
	if( moduleDisplay ){
		moduleId = moduleDisplay.moduleId;
	};
	
	var createdDoc = m.doc;
	
	if( 'module.module1' === moduleId && createdDoc){
		createdDoc.nunaliit_layers = ['layer1'];
	};
	if( 'module.module2' === moduleId && createdDoc){
		createdDoc.nunaliit_layers = ['layer2'];
	};
	if( 'module.module3' === moduleId && createdDoc){
		createdDoc.nunaliit_layers = ['layer3'];
	};
};
````

**Comment by jpfiset** [comment]
Did this work for you?

**Comment by jpfiset** [comment]
In 2.8-SNAPSHOT, a utility can be added to the module to perform the requested work. See documentation here:

https://github.com/GCRC/nunaliit/wiki/Atlas-Builder-Documentation#assign-layer-on-document-creation

This is related to work in Issue #490
