### ISSUE TITLE
Request: Add unselected state on clicking the background in Force Graph

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#479]
**Issue:** When clicking on the background of the Force Graph, the currently selected document remains selected. It would be nice if it's state became unselected (similar to the custom canvas).

**Comment by jpfiset** [comment]
This change forces a change in the way that the background colour is specified. The new method requires SVG attributes to be specified.

````js
    "background":{
    	"fill":"#ddd"
    	,"stroke-opacity":0
    },
````
