### ISSUE TITLE
Suggestion: Add additional wiki markup options

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#487]
**Suggestion:** It would be great if the following wiki markups were supported 
* A markup for images, e.g. [[File:image.png]]
* A markup for block quotes
* A markup for html content not supported by the wiki, eg. <nowiki>

**Comment by jpfiset** [comment]
For images and multimedia, see issue #488

**Comment by jpfiset** [comment]
For sections (blockquotes, alignments), Issue #489

**Comment by jpfiset** [comment]
Rob, the other two issues should address your problems. If so, would you mind closing this issue?

**Comment by boikle** [comment]
Thank you JP.
