### ISSUE TITLE
Wiki markup: Add support for sections

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#489]
To support a wide variety of styles, include a section markup that can specify any attribute.

{{ class="abc" | alt="alt text"
just a line
}}

should translate to:

<div class="abc" alt="alt text">
just a line
</div>

**Comment by jpfiset** [comment]
Should not need the pipes between attributes.

Support HTML attributes: height, width; float, display...

**Comment by boikle** [comment]
Sections have been added to the wiki markup. See wiki on [wiki markup](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#atlas_content_wiki_markup) for more formatting options.
