### ISSUE TITLE
Dynamic point radius for clusters

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#502]
**Idea:** As the cluster count increases so does the point radius of overlay symbol style.

**Comment by jpfiset** [comment]
Initially, I thought this would already be possible. The legacy map style allows computing of attribute "pointRadius". However, it is not possible to make a formula out of it, as the new styling system allows. Therefore, the end result is a cluster which sizes according to the unit of the projection; not useful at all.

The styling system appears to work very well on the new canvas. We have been waiting to rewrite the map canvas to port the map to the new styling system.

However,  if we need to achieve this, it might be expedient to create a legacy map style adaptor for the new style system, allowing using the latest style system in legacy maps.

There are a number of benefits to this approach:
1. Would need to document and maintain only one style system
2. Leaving the old styling system in place would allow us to still support old atlases, but when problem are encountered with styling, move them to the new system
3. End up with richer maps while waiting for the new map canvas

**Comment by boikle** [comment]
It would be great if the new styling system also supported styling of points, lines and polygons based on a defined classification. This would allow for easy creation of Choropleth maps, where polygons have fill and stroke colours applied based on which class the document belongs to.

**Comment by boikle** [comment]
I believe both of these issues have been resolved by the new style system.
