### ISSUE TITLE
Gazeteer point appears in wrong spot with custom projection

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#507]
When using a custom SRS like EPSG 3978 where the units are meters, the geometry created by the gazeteer initially shows up in the wrong spot.

**Comment by jpfiset** [comment]
I tested with custom projection EPSG:32661 and could not reproduce the problem.

What version of Nunaliit is in use?
Would you mind providing your module document?

**Comment by ahayes** [comment]
Was running a 2.2.8 snapshot from May 18. 

Passing layers=reference:landmass,reference:bathymetry to the GeoBase WMS at http://ows.geobase.ca/wms/geobase_en generates pretty much what I want as a background but this bug happens. Use EPSG:3978 for the Atlas of Canada SRS.

**Comment by jpfiset** [comment]
Is this readily available in an atlas?

**Comment by ahayes** [comment]
Not right now. I had to abandon because of the bug.

--
Amos Hayes
Geomatics and Cartographic Research Centre
Carleton University, Canada
http://gcrc.carleton.ca
ahayes@gcrc.carleton.ca
+1.613.520.2600x8179

**Comment by jpfiset** [comment]
Look in history for oceancanada atlas

**Comment by jpfiset** [comment]
I have updated the Ocean Canada atlas with a module to test EPSG:3978. It is located here:

http://atlas.oceancanada.org/index.html?module=module.oceancanada.epsg3978

I have tested the gazetteer and it functions normally. Using this module, can you please provide steps to reproduce problem?

**Comment by ahayes** [comment]
I don't see the problem anymore either. I do see a new problem though... Issue #591
