### ISSUE TITLE
Custom document lists don't show as expected inside wiki documents

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#512]
**Issue:** When showing a custom document list inside a wiki document, the generated div does not contain the contents of the custom document list as expected. Appears to be stuck on the wait stage of the show service. 

Note: A div element is generated, but the div's classes remain as class="n2s_insertedDocumentList n2show_documentList_wait" and don't update to the expected class="n2s_insertedDocumentList" with defined n2-list-type and n2-list-name properties.

**Comment by jpfiset** [comment]
Can you post the line that is inserted in the wiki that causes the issue?

**Comment by boikle** [comment]
**Line from wiki document:** 
```
[[nunaliit:n2s_insertDocumentList|n2-list-type="customList" n2-list-name="gcrcatlas_books&&Cybercartography"]]
```

**Function used for custom document list** (Note: this function works outside of wiki docs)
``` javascript
// Simple function to display a custom list based on a schema type and theme value. 
function handleDocumentListQuery(m){
    if( m.listType === 'customList' ){
	var listOptions = m.listName.split('&&');
        var schemaName = listOptions[0];
        var themeName = listOptions[1];
        
        atlasDesign.queryView({
            viewName: 'nunaliit-schema'
            ,startkey: schemaName
            ,endkey: schemaName
            ,include_docs: true
            ,onSuccess: function(rows){
                var docIds = [];
                var docs = [];
                for(var i=0,e=rows.length; i<e; ++i){
                    if (rows[i].doc[schemaName].theme === themeName) {
                	docIds.push( rows[i].id );
                	docs.push( rows[i].doc );
                    };
                };
                dispatchService.send(DH,{
                    type: 'documentListResults'
                    ,listType: m.listType
                    ,listName: m.listName
                    ,docIds: docIds
                    ,docs: docs
                });
            }
            ,onError: function(err){
                $n2.log('Unable to retrieve document list ('+m.listType+'/'+m.listName+')',err);
            }
        });
    };
};
```

Thanks for the help JP!

**Comment by jpfiset** [comment]
Try:

````
[[nunaliit:n2s_insertDocumentList|nunaliit-list-type="customList" nunaliit-list-name="gcrcatlas_books&&Cybercartography"]]
````

**Comment by boikle** [comment]
This didn't resolve the issue. The class n2show_documentList_wait is still present and no content is shown

**Comment by jpfiset** [comment]
Please, report errors found in console. Also, provide copy HTML element after wiki conversion. Finally, consider the following code:

````js
                var docIds = [];
                var docs = [];
                for(var i=0,e=rows.length; i<e; ++i){
                    var doc = rows[i].doc;
                    if (doc && doc[schemaName] && doc[schemaName].theme === themeName) {
                    docIds.push( doc._id );
                    docs.push( doc );
                    };
                };
````

**Comment by boikle** [comment]
Hi JP, 

Thanks for looking into this issue, 

Unfortunatley no errors were reported in the console (note: I also tried the code with the dispatcher logging everything, and also tried using the debug versions of the nunaliit and nunaliit-couch scripts, and didn't see anything strange was being reported). 

The html element generated is; 
```html
<div class="n2s_insertedDocumentList n2show_documentList_wait" nunaliit-list-type="customList" nunaliit-list-name="gcrcatlas_books&amp;&amp;Cybercartography"></div>
```
Also I tried the code modification you provided and that didn't resolve the issue either.

**Comment by jpfiset** [comment]
This looks fishy:

nunaliit-list-name="gcrcatlas_books&amp;&amp;Cybercartography"

Put a break point in your custom list function and see how this is interpreted.
