### ISSUE TITLE
Extend message options for clustered point pop-up window

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#519]
**Enhancement:** Currently the pop-up message 'this cluster contains {count} features' is the default text shown with clustered points. It may be useful to extend the pop-up messages to include details about the cluster, such as displaying a list/partial-list of doc briefs, or listing a specific key's value from each document. 

**Examples:** 
This cluster contains the documents: 
Doc Brief 1
Doc Brief 2
Doc Brief 3

or 

This cluster contains the locations: Ottawa, Gatineau, Perth

**Comment by jpfiset** [comment]
This should be covered by Issue #525.

See https://github.com/GCRC/nunaliit/wiki/Developer-Documentation#selection-redirector
