### ISSUE TITLE
The n2widget_documentSelector select element size in firefox in Ubuntu 16.04 exceeds module title bar height

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#536]
**OS:** Ubuntu 16.04
**Browser:** Firefox v.47.0
**Issue:** Currently in Ubuntu 16.04 using a Firefox browser, borders are enlarged around select elements, forcing the select element to flow over the module title bar (see screenshot below). This issue does not appear to occur in Safari, Chrome, or MS-Edge, or in Firefox in Windows or Mac OS. 

![selectbreakingmoduletitlebar](https://cloud.githubusercontent.com/assets/6431161/16504066/129a0750-3ee4-11e6-885b-1732a8f741c9.png)
**Possible Solution**: Adding the following style rule (see below) does appear to fix the issue, but likely needs further testing to ensure it doesn't break anything else in the process. 

``` css
.n2widget_documentSelector > select {
    border: 0;
}
```

**Comment by jpfiset** [comment]
The issue is due to a large difference in the user agent style sheet for <select> element, between Chrome and Firefox.

In Firefox:

````
select {
    margin: 0;
    border-color: ThreeDLightShadow;
    background-color: -moz-Combobox;
    color: -moz-ComboboxText;
    font: -moz-list;
    line-height: normal !important;
    white-space: nowrap !important;
    word-wrap: normal !important;
    text-align: start;
    cursor: default;
    box-sizing: border-box;
    -moz-user-select: none;
    -moz-appearance: menulist;
    border-width: 2px;
    border-style: inset;
    text-indent: 0;
    overflow: -moz-hidden-unscrollable;
    text-shadow: none;
    display: inline-block;
    page-break-inside: avoid;
    overflow-clip-box: padding-box !important;
}
````


In Chrome:
````
select {
    -webkit-appearance: menulist;
    box-sizing: border-box;
    align-items: center;
    border-image-source: initial;
    border-image-slice: initial;
    border-image-width: initial;
    border-image-outset: initial;
    border-image-repeat: initial;
    white-space: pre;
    -webkit-rtl-ordering: logical;
    color: black;
    background-color: white;
    cursor: default;
    border-width: 1px;
    border-style: solid;
    border-color: initial;
}
````

The difference in border-width accounts for the discrepancy in the display.

**Comment by ahayes** [comment]
Is this in someone's custom CSS or the demo CSS that we ship? If the latter, can it be made consistent?
