### ISSUE TITLE
timeline widget is not being handled in v.2.2.8

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#543]
**Issue:** Using the sample widgets.json and models.json code provided in the wiki documentation, does not produce a working timeline widget using v.2.2.8 of the framework. The console error (shown below), appears to indicate this widget is not being handled as expected. 

**Console Error:** "Widget handler not found for type: timeline"

**Note:** Using v.2.2.6 of the SDK provides a working version of the timeline widget if the modelType is switched back from "couchDbDataSource" to "couchDb".

**Comment by jpfiset** [comment]
Thanks
