### ISSUE TITLE
Dump documents based on document schema or layer association

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#544]
**Idea:** It would be great if the dump tool supported the dumping of documents based on schema or layer association. 

**Use case:** An atlas has a number of schemas, including one for creating people documents. The atlas owner wants to make a second atlas, and copy all people documents to the new atlas (while maintaining existing doc and rev ids). Being able to dump only documents associated with the schema.people would allow the atlas owner to restore these dumped documents to the new atlas.

**Comment by jpfiset** [comment]
This change would be contained within the "dump" command of the Nunaliit command line tool. This appears useful and not too onerous.
