### ISSUE TITLE
Clustering and Timeline Widget

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#551]
Is it possible to have the time line widget work with clustered data? If not, this may be something worth adding to Nunaliit.

**Comment by jpfiset** [comment]
I do not see why the timeline logic would be incompatible with the way the data is represented on the map. Am I missing something?

Do you have an example where one excludes the other?

**Comment by boikle** [comment]
I tested the use of the timeline widget with clustering and can confirm it works.
