### ISSUE TITLE
Timeline auto updates bounding box extent based on visible geometries

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#552]
Would it be possible to have the map view, auto zoom in on the remaining visible geometries as the timeline widget is changed? This will eliminate the need to zoom in on the portion of the map which contains the relevant data shown by the timeline.

**Comment by decheng-zhang** [comment]
This issue has been resolved with the mapAutoZoom utility.
To use this one, please refer to https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#atlas_utilities_mapAutoZoom
