### ISSUE TITLE
Unable to log into Nunaliit Atlas with IE11 or Microsoft Edge

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#561]
**Issue:** When attempting to login to an atlas with either IE 11 or Microsoft Edge (v.20), the atlas reports an invalid username or password. However using the same credentials in Firefox or Chrome, allows for a successful login.

**Comment by jpfiset** [comment]
I am not able to reproduce this problem. I am able to log in using Microsoft Edge v20.10240.16384.0

**Comment by jpfiset** [comment]
Could you provide me the errors reported by the javascript console?

**Comment by boikle** [comment]
Hi JP, 

This is what the IE 11 console reports and the popup window which is shown. Note: After attempting to login multiple times, once a successful login occured in IE 11 (which I couldn't reproduce, and once I was logged in, the atlas wouldn't let me logout). 

![error_popup_window](https://cloud.githubusercontent.com/assets/6431161/19314225/70519672-9067-11e6-87e8-25e6f6c434a7.PNG)

Upon attempting to login a second time with the same credentials, nunaliit reports both a successful login (which is not indicated in the navbar), and immediately followed by an unsuccessful login message. Note: This successful/unsuccessful dual message has occured before. 

![2ndattempt](https://cloud.githubusercontent.com/assets/6431161/19314226/7054d666-9067-11e6-8210-df8d1cd1b7b2.PNG)

Unfortuntley the console message is just the standard invalid login message, so it doesn't provide much of a hint as to why the identical credentials would work in Chrome or Firefox, but not in IE 11 or Edge.

**Comment by jpfiset** [comment]
After further examination, this is an issue with IE where cache settings are not respected. Turn on option for bad proxy circumvention in

.../tools/debug.html

**Comment by ahayes** [comment]
Have to fix this for users without requiring them to know about this bug and the workaround.
