### ISSUE TITLE
Intersect Model

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#565]
Currently we have a Union (OR) Model which merges multiple models together. Alternatively, it could be useful to have an Intersect (AND) Model which only contains documents that exists in all provided models.

**Comment by jpfiset** [comment]
Yes, I can see how such a model would be useful. However, I am not aware of any atlas that needs it.

**Comment by boikle** [comment]
I agree. Currently I can't think of any existing atlas which needs this feature, but I thought I should mention the enhancement idea in case it's needed in the future. 

Originally I envisioned, both this and the Union model being useful in performing more elaborate document queries.
