### ISSUE TITLE
Changes to Intent in Table Canvas are not being captured post column sort

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#568]
Currently when a table is sorted by a column, the _intentChanged function is no longer called when a user hovers over a cell. Note: This issue does not appear prior to the sort.

**Comment by boikle** [comment]
Adding a this._redraw(); to the end of the _reorderDisplayedRows function in the n2.canvasTable.js, appears to solve the problem. JP can you confirm this an acceptable fix. 

``` javascript
	...
	_reorderDisplayedRows: function(){
		this.sortedRows.forEach(function(row){
			var rowId = row.elemId;
			if( rowId ){
				var $row = $('#'+rowId);
				if( $row.length > 0 ){
					var $parent = $row.parent();
					$row
						.remove()
						.appendTo($parent);
				};
			};
		});
		this._redraw();
	},

...

```

**Comment by jpfiset** [comment]
Although a call to _redraw() would solve that issue, it is much slower in a large table with references. Let me find another approach.
