### ISSUE TITLE
Edits by atlas admin failing on Safari

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#580]
A an atlas admin user has reported that when saving their edits the atlas is popping up the "Submission must be approved" message. Edits are not being applied nor are they showing up in the submission queue.

OS X Yosemite Version 10.10.5 and Safari version 10.0 (10602.1.50.0.10)
Older 2.2.8 snapshot from August 9ish

**Comment by jpfiset** [comment]
I am not able to reproduce this problem. I do not have the exact same components as you:
- Safari 10.0 (11602.1.50.0.10)
- nunaliit2-2.2.8-SNAPSHOT (2016-10-25)

Is it possible to provide me with the logs?

**Comment by ahayes** [comment]
I am not able to reproduce it using
Safari Version 10.0.1 (11602.2.14.0.7) on the same site as the original bug reporter after upgrading it to an Oct 24, 2016 build of 2.2.8. So I'm not sure where the problem lay, but it seems to be OK now.
