### ISSUE TITLE
Uncaught exception when attempting to import geojson coordinates with z values

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#592]
**Issue:** When attempting to import a geojson file with supplied z values, an uncaught exception error occurs. See console error below. 
```
uncaught exception: Only 2D points are supported: -75.31,45.38,0
```
**Suggestion:** Instead of preventing this data from being used, or needing to massage the data to remove the z values from the coordinate x,y,z triples (often provided in geojson data sources). It may be better to either ignore the z values if they exist in the data or support them if they are needed for the map.

**Comment by boikle** [comment]
Example Dataset: http://data.ottawa.ca/dataset/5660afd2-acb0-434d-9b8e-c402bacb48c4/resource/20ae4121-e1ff-41b9-a5ea-8e957cb585ee/download/swamps.json

**Comment by jpfiset** [comment]
The import profile process uses OpenLayers.Format.GeoJSON to parse the GeoJSON. This is the process that returns the error.

**Comment by jpfiset** [comment]
If creating a geometry using a 3rd dimension (in the editor), then the geometry is saved correctly in the database but not rendered on the screen. On the server side, the simplifications are performed correctly.

This looks like a large impact on the system and can not be scheduled for 2.2.8

**Comment by jpfiset** [comment]
The dataset given in example, above, is too large for purpose of testing.

````json
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "SHAPE_Leng": 51.501461384400002 }, "geometry": { "type": "LineString", "coordinates": [ [ -75.318913873296793, 45.38066305392455, 0.0 ], [ -75.318702279238138, 45.380399902924857, 0.0 ], [ -75.318715980957208, 45.380355051415108, 0.0 ], [ -75.318754842720153, 45.38032845743399, 0.0 ], [ -75.318857533766746, 45.38030252359556, 0.0 ] ] } },
{ "type": "Feature", "properties": { "SHAPE_Leng": 5.09911757409 }, "geometry": { "type": "LineString", "coordinates": [ [ -75.318857533766746, 45.38030252359556, 0.0 ], [ -75.318921552980157, 45.380294187033108, 0.0 ] ] } },
]
}

````

**Comment by boikle** [comment]
Tested importing a geojson file with z values, and can confirm that the z values no longer cause and exception error.
