### ISSUE TITLE
Data Modification Query results show doc id not doc brief

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#608]
I've noticed that sometimes query results in the data modification tool, show a list of document doc ids instead of the document briefs. However, once a user mouses over a doc id, the doc id string is replaced with the document's brief. 

I'm not sure if this is a feature (i.e. minimize use of the screen with one doc per line), or a bug? 

Note: This functionality was experienced in an atlas running v.2.2.8.

**Comment by jpfiset** [comment]
When the list of documents is very long, then the UI stalls attempting to get all documents to display the brief. This delay was deemed non-productive. If the list is short, then all document contents are retrieved and the briefs are displayed. If the list is long, then only the document id is displayed, until the user mouses over.
