### ISSUE TITLE
Add ability to have map initial extents centred on user

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#627]
There are situations where an atlas should be centred on a user's location. Add an map auto initial bounds based on the geolocation returned by the browser.

Add ability to adjust only the latitude or the longitude.

**Comment by jpfiset** [comment]
In map.json definition:

````json
{
	...
	,"coordinates": {
		"initialBounds": [-140,50,-54,77]
		,"autoInitialBounds": {
			"type": "mapAutoInitialBoundsCentreOnUserPosition"
			,"adjustLatitude": false
			,"adjustLongitude": true
		}
	}
}
````

**Comment by pulsifer** [comment]
Recall that this is already implemented for arcticbm.org, so there may be potential to reuse some code.

**Comment by jpfiset** [comment]
Peter, you are correct.

**Comment by jpfiset** [comment]
Currently, this feature works with Firefox. It does not work with Chrome unless the atlas is served over HTTPS. In Chrome, an error is returned:

PositionError
message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."
