### ISSUE TITLE
Short video results in upload failure

### ISSUE THREAD

**Issue by billingb** [GCRC/nunaliit#655]
When a video clip of 3 seconds is uploaded the upload will fail to be processed completely due to a failure to generate the thumbnail for display. This will leave the video in a processing state with a spinner forever.

Two things could be done to resolve this issue.
1) If the thumbnail is not generated a stock one should be used and processing should complete.
2) The thumbnail generation could detect the length of the video clip and adjust accordingly.

**Comment by jpfiset** [comment]
I think that this was addressed in Issue #671. Can you verify that it meets your requirements?

**Comment by billingb** [comment]
#671 fixed this issue.
