### ISSUE TITLE
Error when running new Atlas created using 2.2.9-SNAPSHOT

### ISSUE THREAD

**Issue by rodolpheg** [GCRC/nunaliit#662]
Hello,

I am trying to run an atlas I freshly created using the latest 2.2.9 snapshot (built from the cloned git source according to the developper doc).

As I run, I get this error message (among other, here is the full log: https://www.dropbox.com/s/ju4fs18ihk0s5zd/Error%20message%20runing%20nunaliit%20atlas.txt?dl=0):

"2017-05-30 11:11:15,539[ERROR]: Error starting upload worker
org.json.JSONException: JSONObject["last_seq"] is not a number."

Any idea where this issue could come from?

Thanks!

**Comment by jpfiset** [comment]
Can you provide the lines in the logs following the one you are reporting?

**Comment by ahayes** [comment]
Hey JP. I'm just seeing this now. It looks like he links to the full log. Can you have a look at it?

**Comment by billingb** [comment]
Was this issue resolved? I'm seeing exactly the same issue as the above log and I just don't see anything that is pointing me at what the root problem is.

**Comment by ahayes** [comment]
This looks like an error we saw when we first tested with CouchDB 2+. Current builds should support CouchdDB 2.1.1. See issue #733 for details on when the support was added.

**Comment by billingb** [comment]
@ahayes Thanks it was a mistake in our scripts that was using an older Nunaliit version, upgrading fixed the issue and I've got a working atlas now!

**Comment by francoislanoe** [comment]
Running in the same issue. I am not a developer and am using the latest package available 2.2.7 from 2016. Any instructions on how to fix this for someone not too well-versed into programming?

**Comment by francoislanoe** [comment]
OK, much trial and error, but figured out how to use Maven. Coffee.

**Comment by boikle** [comment]
Hi @francoislanoe, I'm glad you were able to sort out your issue on your own. If you have any questions in the future, don't hesitate to contact us. The GCRC is always happy to help.

**Comment by ahayes** [comment]
I have updated http://nunaliit.org with a new link to point to our GitHub releases page for latest builds. There is still a bit more to do to automatically clean out previous builds, but it should save people from having to learn how to build Nunaliit.
