### ISSUE TITLE
Protecting atlas with basic auth

### ISSUE THREAD

**Issue by billingb** [GCRC/nunaliit#675]
I'm trying to make an entire atlas private by using basic auth (nginx) in front of the atlas to protect it. It does not appear to be working correctly as the basic auth succeeds to log into the nginx server and then results in a failure for logging in to the atlas which appears to also use basic auth.

Has anyone used this method (or another) successfully to make an entire atlas private? If so can you share a little of how the atlas was setup?

Thanks,
  Brendan

**Comment by billingb** [comment]
I solved this issue. NGINX needs to be configured to remove the Authorization header as described here: https://cwiki.apache.org/confluence/display/COUCHDB/Nginx+as+a+proxy#Nginxasaproxy-Authenticationusingnginx

The setup I have that is working is:
location / {
    proxy_pass http://127.0.0.1:8080;
    auth_basic "Restricted";
    auth_basic_user_file htpasswd;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Authorization "";
    add_header X-Auth-CouchDB-UserName $remote_user;
  }

**Comment by ahayes** [comment]
Ah yes. Sorry I just saw this now. If you have a look at the very end of the prerequisite install docs, we talk about setting Nunaliit up behind Apache. If you wanted to add a section for setting it up behind Nginx, that would be cool. Note the last line of the Apache instructions handle this same issue.

https://github.com/GCRC/nunaliit/wiki/Prerequisite-install-on-Ubuntu-16.04-LTS
