### ISSUE TITLE
Add ability to specify pretty print in nunaliit dump command

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#68]
During the "nunaliit dump" command, one should be able to specify that the JSON object saved to disk be formatted in a manner easily read by humans. This is to facilitate the off-line editing process where a user dumps a document, updates it and then push it back up to the database (restore)

**Comment by boikle** [comment]
Is this still an issue? Currently the dump tool does dump out a pretty print JSON documents, which can be restored.
