### ISSUE TITLE
'Find on Map" function in Nunaliit 

### ISSUE THREAD

**Issue by sapyne** [GCRC/nunaliit#682]
When there are many points and/or many layers and/or a timeline, it is often almost impossible to identify the relevant point when "find on map" is clicked on.

Can the 'find on map' function be enhanced to allow points to be identified better?

**Comment by ahayes** [comment]
An atlas builder can choose the style of any "found" geometry. In 2.2.9, this should be done in the conditional styling system. See: https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#conditional-map-styling

It is also possible to do this in the older (deprecated) style system via the "find" intent.
