### ISSUE TITLE
Enhanced Tag - Document Relation Function

### ISSUE THREAD

**Issue by sapyne** [GCRC/nunaliit#683]
We would like to (1) relate multiple documents and have the ability to add a tag to indicate they are part of the same group and (2) have a more automatic way to relate the documents.

So far, the process of relating nine documents has involved quite a few identical "add relation" actions. For the ninth document, I had to add eight separate relations. These nine docs are all part of the same grouping (a plan).

We would like to be able to create a tag for this plan, and then assign this tag to each relevant record.

**Comment by ahayes** [comment]
In 2.2.9, models should be used to group documents for various purposes. See docs.
