### ISSUE TITLE
option to turn off media download button

### ISSUE THREAD

**Issue by cmcneave** [GCRC/nunaliit#685]
Hi all.  One of our partners has asked to have the media download button removed from all media play/display windows.  It is understood that by just posting media on the internet there is a loss of control.  But in the interest of keeping the content under control of the community, the partners do not want to offer a media download option.  I have checked the documentation may have missed it, but I'm wondering if there is a way to universally turn off the media download button for an atlas.

Thanks.

Chris McNeave

**Comment by ahayes** [comment]
Hi Chris. I would inspect that element of the page and see if there is a unique class you can refer to for the download button or its container. Then you can try setting display to none for that class in CSS.

**Comment by cmcneave** [comment]
Thanks, Amos.  That did it.  I added

.n2DisplayBoxButtonDownload {
	display:none;
}

to altas.css

Regards,

Chris McNeave

**Comment by boikle** [comment]
This issue appears to be resolved so I'm going to close it

**Comment by ahayes** [comment]
Cool. Just so it is clear, the full media files can always be downloaded by someone who knows what they are doing. Same as youtube and elsewhere. If you are sending it to the browser to show, it is downloadable. All this is doing is making it non-obvious as an option.
