### ISSUE TITLE
Not able to zoom in on WMS background map

### ISSUE THREAD

**Issue by pulsifer** [GCRC/nunaliit#688]
We have established a module using a WMS to display an airphoto background map.  The configuration information is below.  

When accessing the module, zooming out works as expected, however zooming in beyond one level does not work.  We have tested the WMS directly using the GeoServer layer preview function (OpenLayers) and are able to zoom to a high level of detail without an issue.

We have experimented by changing the initial zoom levels from 19 to 40 with no change in behaviour.

The initialBounds are relatively small (around 7000 meters in the X dimension).  They were originally smaller, however increasing had no effect.  We have tried with and without autoinitialBounds.

Not clear on the reason for this behaviour.  Wondering if there is some type of minimum scale limit set by default?

Have tried with latest versions of Chrome, Safari and Firefox.

Module map.json

"coordinates": {
		"initialBounds": [513000,7813500,520000,7820000]
		,"autoInitialBounds": false
		,"srsName": "EPSG:26919"
	}
	,"backgrounds": [
			  	   {
	         "id": "airphotowms"
	         ,"name": "Air Photo"
	         ,"type": "wms"
	         ,"options": {
	            "layers": "clyderiver:A21157_EPSG26919_PYRAMID"
	            ,"url": "https://[service_url]/geoserver/clyderiver/wms?"
		        ,"srsName": "EPSG:26919"
		        ,"numZoomLevels": 40  #was 19
	         }
	      }
	]

**Comment by pulsifer** [comment]
Note that we are running latest 2.2.9-SNAPSHOT on Ubuntu 04-16

**Comment by pulsifer** [comment]
Any thoughts on this issue?

**Comment by jpfiset** [comment]
A quick look reveals that the base layer associated with this map has 16 zoom levels. When the map is first loaded, it settings are such that it is already at zoom level 14. Zoom in once, and the last level (15) is reached.

I need to investigate why there are not more zoom levels.

**Comment by pulsifer** [comment]
Thank you.  In case this is relevant, when first exploring, we attempted to increase and decrease the number of zoom levels (to 32 and 8, if I recall).  This did not seem to change the behavior.

**Comment by jpfiset** [comment]
I made a change and pushed it to the atlas. It is re-indexing.

**Comment by jpfiset** [comment]
Looks fixed.
