### ISSUE TITLE
Text formatting options for Form View

### ISSUE THREAD

**Issue by cmcneave** [GCRC/nunaliit#738]
Hi. We've come across the need for some basic text formatting capabilities when entering or editing content in Form View.  Basic things like line breaks, headings, bold, etc. that Wiki Markup can do would be really helpful if the formatted text could then be seen in the side text panel.

Do you have any thoughts on where to start looking for possibilities for this?

If implemented I see this as a frequently used feature.  The particular atlas where this is needed is running Nunaliit 2.2.9-SNAPSHOT.

Thanks.

Chris McNeave

**Comment by ahayes** [comment]
Hi Chris. If you search the Nunaliit Atlas Builder Documentation for "wiki" you should find information about the "wikiTransform" option you can set on a string field to have it accept wiki markup.
