### ISSUE TITLE
Add "Remove" action to queries in doc modification tool

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#743]
It would be good to be able to refresh and remove queries in the document modification tool.

This would be helpful when making changes to documents so that you don't need to refresh the page and build your list of queries again every time you make some modifications and want to see the changes reflected in query results.

**Comment by boikle** [comment]
Remove action has been added to queries in doc modification tool.

**Comment by ahayes** [comment]
New issue #874 created for "refresh". Closing this one.
