### ISSUE TITLE
Add search constraint support for models

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#757]
Search constraint functionality needs to be extended to support filter constraints by documents found in the module model.

**Comment by boikle** [comment]
Notes: 
* Existing "constraint" key in search.json should be renamed to indicate its for layers. E.g. layer_constraint
* If possible also add a constraint for schemas. E.g. schema_constraint

**Comment by ahayes** [comment]
Existing contraint key should be plural as it expects an array. So "constraint_layers",  "constraint_schemas", and "constraint_models" would be better. Also, in a configuration with lots of keys, they will sort next to each other.

**Comment by boikle** [comment]
After working on this, I've changed the constraint key to be an object with a property key for type and an array specifying the constraint. 

E.g. 
```json
constraint: {
"type": "layers",
"layers": ["foo", "bar"]
}
```
