### ISSUE TITLE
Push builds to from Travis-CI to GitHub releases

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#776]
We should be able to push Nunaliit the Nunaliit builds that Travis-CI does to the project's releases page. It would be good to push latest and release-tagged commits.

**Comment by boikle** [comment]
I believe this issue has been resolved.

**Comment by ahayes** [comment]
The link with Travis CI became problematic again. @alexgao1 switched us over to a [GitHub Workflow](https://docs.github.com/en/actions/using-workflows) with https://github.com/GCRC/nunaliit/pull/1124.
