### ISSUE TITLE
Drag & Drop components in Schema Builder misaligned to cursor position

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#790]
**Issue:** When the schema builder form builder view exceeds the window's height and the user scrolls down the page to place a new component, their is a gap between the user's mouse position and the dragged component. This behaviour makes the dropping of a component difficult for users. 

Note: This issue was replicated on two different systems, both using chrome browsers.

**Comment by boikle** [comment]
After testing the change, this issue still persists. 

**Situation:** When there is multiple items (more than a screen height's worth) in the form builder, if you attempt to move one of those items to a different position, the draggable item is misaligned with the cursor position. This appears to prevent the moving items in the form. 

**Potential Enhancement:** It would be nice if the form builder scrolled to allow a user to drop items in different positions on the form. Currently it doesn't appear to do this automatically in either chrome or firefox.

**Comment by decheng-zhang** [comment]
The enhancment has been implement in pull request https://github.com/GCRC/nunaliit/pull/801
Waiting for code reviewing

**Comment by decheng-zhang** [comment]
The pull request:801 fix the issue in branch:master;
commit:66034bd fix the same issue in branch:2.3.0-alpha causing by material-design css;
