### ISSUE TITLE
Reference array abandoned edit leaves null element value

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#802]
When editing a document with an array attribute containing references, the user typically clicks in the text field which prompts a document search dialog. If the user cancels the search and saves the document without populating the field, the first element of the array winds up with a null value. Instead, the array element should not exist.

**Comment by boikle** [comment]
I found an issue with this fix which is preventing empty arrays from being populated with values. 

**Use Case Example:** 
I have a document which has an empty nunaliit_layers array. 

1. I edit the document either with the layer dialog window, or through the tree view.
2. I add one or more strings (layer names) to the nunaliit_layers
3. Save the changes to the document
4. Console reports the message "An all null Array nunaliit_layers has been detected and corrected"
5. The array is emptied.
