### ISSUE TITLE
Openlayers error message after "d" key is pressed in an input field in form view.

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#813]
**Error messages observed in console:** 
Chromium - "Uncaught TypeError: Cannot read property 'target' of null"
Firefox   - "TypeError: evt is null"

**Steps to reproduce the bug**
1) Create/Edit a demo document
2) Click on an text input field in the form view
3) Type the letter "d" 

**Additional Note:**
Although the above steps do frequently reproduce this bug, its reproducibility does seem infrequent after the initial error is reported, or if a unknown period of time passes.

**Comment by decheng-zhang** [comment]
Fix have been created and merge in pull request 833
