### ISSUE TITLE
Geometry Style Rules in Legacy map style system over-ride all base styles

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#817]
**Issue:** According to the wiki documentation, the legacy style rules should follow the order of; 
default styles < base styles < geometry styles < layer styles < schema styles < intent styles.

However in the n2.mapStyles.js _computeStyleSet method (line 374), geometry styles are applied after the base styles, which overrides the previous base styles. This is correct, except the layers, schemas, and intents all have there own base styles as well and are being added to the style set before the geometry styles, which I suspect is causing them to be overridden. 

Credit goes to @billingb for finding this bug.

**Comment by decheng-zhang** [comment]
The legacy style system will be deprecated in the 2.3.0 release. We probably won't fix this.
