### ISSUE TITLE
Java >8 compatibility

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#819]
Upgrade Nunalii to run in latest OpenJDK versions (greater than version 8).

**Comment by ahayes** [comment]
Created [branch 819-Build_on_Java_11](https://github.com/GCRC/nunaliit/tree/819-Build_on_Java_11) to store my efforts so far. Does not build yet. Have basically been stumbling over maven plugin versions that don't support Java 11, at least up until nunaliit2_gpx where we have lost tools.jar in Java 11 and pulling the dependency out of the pom didn't fix it. I'm not sure how to move ahead.

**Comment by NassefAsh** [comment]
Updated versions in ./pom.xml for Java 11 support, and added javax.activation dependency in ./nunaliit2-gpx/pom.xml. It builds correctly, but requires couchdb 3.2.2 for atlas to display correctly.

**Comment by ahayes** [comment]
> but requires couchdb 3.2.2 for atlas to display correctly.

Did you mean 2.3.1? Ash, you could always test the Java 11 build on Ubuntu 18.04 with couchdb 2.3.1 while we look into a build for Ubuntu 20.04.

**Comment by NassefAsh** [comment]
Apologies, that could have been clearer.

I have not tested the Java 11 build on Ubuntu 18.04. I tested on Ubuntu 20.04, and AFAIK you can't install CouchDB 2.3.1 on 18.04. CouchDB 3.2.2 is required for Ubuntu 20.04. However, when tested with CouchDB 3.2.2, all scripts from index.html, lines 62 - 84 (inclusively) did not load properly. This requires further investigation.

As for building on Java 11, the changes in the PR will allow Maven to build successfully.

**Comment by ahayes** [comment]
Closed by PR #1112
