### ISSUE TITLE
Import tool fails with "An import profile must be provided"

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#832]
I have created a geojson import profile and it appears correctly in the import tool. After pasting in my geojson and clicking "Verify", a dialog pops up saying "Missing input. Can not proceed." and the log shows "An import profile must be provided". The verification does not proceed.

**Comment by decheng-zhang** [comment]
This issue relates to a bug in the recent change of import.js for migrating to material design MDCSelect Object. Since the branch:Master is not using material design yet. The fix is now merged into 'branch-for-atlascine' and will eventually be merged in next milestone of nunaliit
