### ISSUE TITLE
In 2.3.0-alpha: occasionally after a refresh, couchEditor will append different views (tree| form) together

### ISSUE THREAD

**Issue by decheng-zhang** [GCRC/nunaliit#834]
In 2.3.0-alpha (The branch with ol5 and mdc). The couchEditor occasionally will merge different view (tree view or editor view) together after a refreshing.
To reproduced the issue:
1. Click the button ADD RELATION
2. Select a candidate doc from the search dialog
3. Often after the refreshing, tree view and editor view will both showing in side panel
Potential cause: 
Some issue in couchShow service relating to the mdc class creation

**Comment by decheng-zhang** [comment]
The fix has been committed to 2.3.0-alpha. We will further test it. But since tab-style of couchEditor is expected to be introduce in 2.3.0-alpha, instead of the jquery-ui accordion,
`			window.setTimeout(function(){
				$elem.removeAttr('style');
			},500);`
seems no longer necessary.

**Comment by boikle** [comment]
I've removed this timeout and the width and height style changes from the n2.schema.js. 

This change has been pushed into both the 2.3.0-alpha and the mdc_integration branches.
