### ISSUE TITLE
more than one type of media per schema?

### ISSUE THREAD

**Issue by sapyne** [GCRC/nunaliit#845]
It would be nice if photo or video media that is uploaded to a media schema could have the option for audio or video capture via nunaliit to be incorporated in the same schema doc.

it is currently a select file or audio or video option.

at this link, I created a separate doc for the test audio and related it to the doc with the uploaded file. 

the schema form must have a selection option for file, audio or video.

could a checkbox group option be offered instead - this will allow the person uploading a file to a media doc to be able to comment on it within the same document. 

here is the example: https://lhta.ca/rsplanning/index.html?module=module.travels#eyJ0IjoieCIsImkiOiJhY2JiZGE0MDA0MDNiNTI5MzJkYjI3MTI2ODU4M2UxMyIsInMiOjE1NzE1NzE3NDIxOTN9
![image](https://user-images.githubusercontent.com/31515146/67159000-142b0980-f30d-11e9-90e9-e0959e1b9576.png)

**Comment by boikle** [comment]
In past experience, we've found it more flexible to separate media as individual media schema documents and relate each one individually to another type of document. 

This provides the potential benefit of one media document being related to multiple documents, which gives the advantage of not needing to be uploaded multiple times, and provides a individual document in which to associate other documents (e.g. a comment document). 

However we do appreciate your insights on the process, and perhaps improvements can be made to the media upload workflow for situations when you want to capture audio or video in relation to another media document.

**Comment by sapyne** [comment]
Thanks Rob,

I realize the preferred option is to create a new media doc and relate it to the media doc with the media being commented on. 

Maybe I can explain further in person with you and Amos why I still think it may be a good option for the original creator of a media doc to be able to add an audio or video comment while in the same media doc.

**Comment by sapyne** [comment]
Actually, separating the media as individual media schema documents should be fine, if an add related item dropdown can be included for in media schemas that may have media that will be commented on via audio or video - I was partly thinking about ease of use for users.
