### ISSUE TITLE
Legend widget checkboxes

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#859]
The model-driven legend widget needs to have the option of also being a filter widget that includes or excludes documents based on their membership in a style set. It should be possible to reproduce the functionality of old openlayers legend widget with checkboxes next to the "layers".

Note: This may be infeasible if based on style conditions and may require an atlas builder to structure models and filters accordingly so that the checkboxes are operating on specific filters and the styling is operating on specific results. Some exploratory work and discussion required.

**Comment by boikle** [comment]
I believe this was resolved with the new LegendWidget2 addition. @decheng-zhang can you confirm this can be closed?

**Comment by decheng-zhang** [comment]
Yes, it sounds like what widgetlegend2 is trying to achieve. I suggest to close this issue for now.
