### ISSUE TITLE
Replace "fbi_dude.png" with an icon portraying consensus

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#892]
We need to replace the FBI dude with something less authoritarian. Please replace it with the attached "consensus" icon (albeit scaled down). This is shown when an `Attachment is waiting for approval`.

![consensus](https://user-images.githubusercontent.com/1750076/76249678-408ee600-621a-11ea-94b5-417ceee4dc8e.png)

**Comment by boikle** [comment]
The image has a diagonal watermark. Do you have a version without the watermark?

**Comment by ahayes** [comment]
Here is a version re-drawn by Imogen.
[Consensus Icon.zip](https://github.com/GCRC/nunaliit/files/4314347/Consensus.Icon.zip)
