### ISSUE TITLE
Revert default audio codec to MP3

### ISSUE THREAD

**Issue by sruest** [GCRC/nunaliit#911]
The default audio codec was changed to AAC from MP3.  Amos pointed out that this may be an issue in older browsers, since some of them don't support AAC.  Revert the audio codec to MP3 for audio file conversions.  Video files should still use AAC for their audio.

Introduced by #906

**Comment by ahayes** [comment]
Yep. Actually, it is Firefox that still doesn't support it outside of video containers. See https://caniuse.com/#search=aac
