### ISSUE TITLE
userX issue with search results from other modules

### ISSUE THREAD

**Issue by sapyne** [GCRC/nunaliit#922]
Could there be a way to change the map display for search results that appear in the side panel but that are from a different map than a user may be in, possibly from within a selected record?

**Comment by boikle** [comment]
Hi @sapyne, 

Thank you for the question. Currently Nunaliit provides a mechanism to allow atlas builders to constrain search results in a module. See the first code block in the following [atlas builder wiki section](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#module-document) for an example of how search constraints work.

So in theory you can control what documents can be shown in the search results in the side panel using this technique. 

I hope this answers your question.
