### ISSUE TITLE
Support CouchDB 3.x

### ISSUE THREAD

**Issue by eilanlaken** [GCRC/nunaliit#935]
The cause of this error is a variable set in the local.ini in the couchdb bin folder:
users_db_security_editable = false

**Comment by ahayes** [comment]
We need to look into this and see if undoing a default in couchdb is really necessary or if we can adapt Nunaliit to work within the new couchdb defaults. We need to learn more about their change and what risks are associated with changing that default. If we can do the later without too much effort, and while remaining backwards compatible with couchdb 2.x, that would be my preference.

**Comment by ahayes** [comment]
Any updates on this @eilanlaken? @billingb could use some info on what you found.

**Comment by billingb** [comment]
Some additional info. 
From the docs: https://docs.couchdb.org/en/3.2.0/config/couchdb.html#couchdb/users_db_security_editable

Best starting point for the code: https://github.com/GCRC/nunaliit/blob/master/nunaliit2-couch-user/src/main/java/ca/carleton/gcrc/couch/user/UserServlet.java#L183

**Comment by billingb** [comment]
Here are the steps I've taken to get an atlas that loads using couchdb 3.

1.  Machine is WSL2 Ubuntu 20.04.1 LTS
1. `sudo apt-get install couchdb` and setup standalone
1. In webbrowser go to http://localhost:5984/_utils and click on wrench (setup, second item in menu). Configure for standalone usage. This creates the _users and _replicator DBs.
1. Edit ‘/opt/couchdb/etc/local.ini’
  a. add new line ‘users_db_security_editable = true. 
  b. uncomment max_document_size line
  c. Uncomment ‘require_valid_user = false’ line
1. Edit ‘/opt/couchdb/etc/default.ini’
  a. Set ‘default_security = everyone’
1. `nunaliit create` to create atlas
1. `cd testatlas` -> `nunaliit update` -> `nunaliit run`

**Comment by ahayes** [comment]
I followed these steps on Ubuntu 20.04.4 LTS with couchdb 3.2.2 and openjdk-11-jre-headless and the atlas does not fully load in the browser. I don't see any relevant browser console errors. Same with latest Chrome and Firefox on macOS.

<img width="1016" alt="Screen Shot 2022-08-25 at 12 25 52 AM" src="https://user-images.githubusercontent.com/1750076/186574804-d7104b90-c8a7-41ac-9e20-e9c810bdcc2b.png">

**Comment by billingb** [comment]
Couple of thoughts:

1. I had to fix a bug in the code. That was merged in this pull request: https://github.com/GCRC/nunaliit/pull/1076 Can you verify that you are running a Nunaliit build that includes that change?
1. I realized I didn't have restart the couchdb on the list. Can you try deleting the DB, restarting couch and then re-update and run the atlas?
1. If neither of those steps fix the problem I also ran this command but I think this wasn't needed: `curl user:password@localhost:5984/_users/_security -XPUT -d '{}'`

**Comment by ahayes** [comment]
https://github.com/GCRC/nunaliit/pull/1076 fixed it.

**Comment by billingb** [comment]
I've fixed the non-loading tools pages. I've updated my comment above with steps, the new step is step 4 in that list with modifying default.ini.

**Comment by ahayes** [comment]
In general, we shouldn't be asking people to adjust default.ini as local changes are supposed to be applied in local.ini which overrides default.ini. I believe that is what the couchdb package expects as well.

@billingb  Do you know of a necessity for your Step 4 changes to be in default.ini? If not I will test putting them in local.ini and see how that goes.

**Comment by billingb** [comment]
@ahayes I made the changes from instructions I found for fixing the issue but you're right that local.ini would make more sense and hopefully the changes can be moved there.

**Comment by ahayes** [comment]
I moved the changes to local.ini and all seems well. Can you provide a bit more info about those changes? (i.e. what changed in couchdb and how it affected Nunaliit?)

An unrelated problem I noticed in testing, which I will have to investigate a bit more before creating an issue, is that the test video I had put in that atlas but couldn't approve because of this issue, wound up with out of sync video and audio.

**Comment by billingb** [comment]
Those setting in 4 are setting security back to couchdb 2 defaults. Security is a lot more locked down in 3 by default and I think it will be a lot of work to support those changes.

**Comment by ahayes** [comment]
FYI, creating a new email user and logging in is broken in CouchDB 3.3.1.
Browser console:
```
Unable to obtain user information: Error obtaining user document for org.couchdb.user:user-770716164: You are not allowed to access this db. nunaliit2.js:233:634
Login error Unable to obtain information about user nunaliit2.js:233:634
Object {  }
 Unable to obtain information about user nunaliit2.js:233:811
    logError https://bekh.gcrc.carleton.ca/nunaliit2/nunaliit2.js:233
    reportError https://bekh.gcrc.carleton.ca/nunaliit2/nunaliit2.js:234
    reportErrorForced https://bekh.gcrc.carleton.ca/nunaliit2/nunaliit2.js:234
    onError https://bekh.gcrc.carleton.ca/nunaliit2/nunaliit2.js:2706
    t https://bekh.gcrc.carleton.ca/nunaliit2/nunaliit2.js:2686
    k https://bekh.gcrc.carleton.ca/nunaliit2/nunaliit2.js:2686
    onError https://bekh.gcrc.carleton.ca/nunaliit2/nunaliit2.js:2679
    error https://bekh.gcrc.carleton.ca/nunaliit2/nunaliit2.js:2102
    jQuery 4
```

**Comment by billingb** [comment]
@ahayes I've been unable to reproduce the issue you're seeing. I have tried running the atlas with two setups. Setup 1:
* couchdb 3.2.2
* ubuntu 20
* open java 11.0.2

Setup 2:
* couchdb 3.2.2
* ubuntu 18
* open java 1.8.0_292

If you are still seeing issues try running this command `curl user:password@localhost:5984/_users/_security -XPUT -d '{}'`

**Comment by billingb** [comment]
> Couple of thoughts:
> 
> 1. I had to fix a bug in the code. That was merged in this pull request: [Fix undeclared variable error. #1076](https://github.com/GCRC/nunaliit/pull/1076) Can you verify that you are running a Nunaliit build that includes that change?
> 2. I realized I didn't have restart the couchdb on the list. Can you try deleting the DB, restarting couch and then re-update and run the atlas?
> 3. If neither of those steps fix the problem I also ran this command but I think this wasn't needed: `curl user:password@localhost:5984/_users/_security -XPUT -d '{}'`

Step 3 fixed the issue. Guess that is needed.

**Comment by ahayes** [comment]
I have created a new [Prerequisite-Install-on-Ubuntu-20.04-Server](https://github.com/GCRC/nunaliit/wiki/Prerequisite-Install-on-Ubuntu-20.04-Server) wiki page that captures the CouchDB config documented in this issue. We can make a new issue when it comes time to explore CouchDB's security model a bit more. As it stands, we leave it to Nunaliit to manage write access to the databases.
