### ISSUE TITLE
Legend Widget not appearing

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#939]
When configuring a legend widget as described in the [Atlas Builder Guide](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#atlas_widget_legend), the legend div is inserted into the DOM but is empty. The legendWidget object is created and logged to the console (at least when running nunaliit-debug.js in place of nunaliit.js in index.html). This worked in the past but I am seeing this bug back in June and July 2020 builds. Could be related to issue #859 or issue #820

**Comment by ahayes** [comment]
I would start looking at https://github.com/GCRC/nunaliit/blob/master/nunaliit2-js/src/main/js/nunaliit2/n2.couchModule.js and  https://github.com/GCRC/nunaliit/blob/master/nunaliit2-js/src/main/js/nunaliit2/n2.widgetLegend.js and using the web inspector to set some breakpoints and step through.

**Comment by billingb** [comment]
In a code commit from April, 2020 there was logic introduced to prevent the legend widget from being displayed unless a label provided in init of the widget was matched by a style. Many atlases do not provide labels to the init of the widget label. You can see the commit here: https://github.com/GCRC/nunaliit/commit/81ad0f82f2e2488024469366d2ec313cb4c52adf

**Comment by ahayes** [comment]
Thanks for fixing that. There was a time when the widget would appear as a little empty box in the UI even if nothing was trying to display in it. I think that is what the commit was trying to deal with but if you have found a way to have it be more backwards compatible, that is great.
