### ISSUE TITLE
Enhancement: Add some documentation for creating the "geometry" type in a schema

### ISSUE THREAD

**Issue by adamstone7** [GCRC/nunaliit#944]
An example of the "geometry" type in a schema is missing from the atlas content schema definition in the Nunaliit documentation for atlas  builders. Adding this would help show _geometry's_ unique layout.

**Comment by ahayes** [comment]
I don't believe there are any unique options for that type. If you are using schema definition files, you define an attribute of type geometry with a unique id and that's it. If you want to see it during "display" or "brief" renderings, check that you have set the relevant boolean options. The docs are at https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#schema-definition and you are looking for the list of attribute types. "geometry" is in there.

If I have misunderstood, please comment again with more details on what you need and I will re-open.
