### ISSUE TITLE
CouchDB 2.3.1~bionic repo no longer supported

### ISSUE THREAD

**Issue by adamstone7** [GCRC/nunaliit#947]
As of May 1, 2021, the Bintray repo holding CouchDB 2.3.1~bionic was shut down permanently. No new repository containing this version of CouchDB has surfaced since. Erlang 17.04 is required to build from source. However, current CouchDB installations cannot seem to use anything earlier than Erlang 19.0 when building from source (see [https://github.com/apache/couchdb/issues/1945](https://github.com/apache/couchdb/issues/1945)). 

This issue will be solved when an active repository is found or a successful workflow for building from source is established. If we expect the need to build from source for the foreseeable future, we should consider containerizing Nunaliit and its requirements (or at least its requirements and install latest Nunaliit build on top).

**Comment by billingb** [comment]
I've updated the prereq install instructions at https://github.com/GCRC/nunaliit/wiki/Prerequisite-install-on-Ubuntu-18.04-LTS

Please let me know if this addresses the issues you are seeing.

**Comment by billingb** [comment]
Adam has a working environment now using these instructions.
